AWSTemplateFormatVersion:  "2010-09-09"
Description:  This templates creates a VPC and an EC2 instance
Resources:
  coleVPC:
    Type:  AWS::EC2::VPC
    Properties:
      CidrBlock:  10.0.0.0/16
      EnableDnsHostnames: 'false'
      EnableDnsSupport: 'false'
      InstanceTenancy: default
      Tags:
      - Key:  vpccfstack
        Value:  development

  ColeEC2Instance:
    Type:  AWS::EC2::Instance
    Properties:
      ImageId: "ami-0d5eff06f840b45e9"
      InstanceType: "t2.micro"
      KeyName: "cfvpcec2KeyPair"
      NetworkInterfaces:
        - AssociatePublicIpAddress:  "true"
          DeviceIndex: "0"
        